<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;

class AgentsSeeder extends Seeder
{
    public function run()
    {
        $agents = [
            [
                'user' => [
                    'name'  => 'Moussa Diallo',
                    'email' => 'moussa.diallo@teranga-immo.sn',
                ],
                'fournisseur' => [
                    'nom'             => 'Diallo',
                    'prenom'          => 'Moussa',
                    'adresse'         => 'Almadies, Route de Ngor, Dakar',
                    'telephone'       => '+221 77 123 45 67',
                    'name'            => 'Teranga Premium Immo',
                    'description'     => 'Spécialiste de l\'immobilier haut de gamme aux Almadies et à la Corniche. Plus de 12 ans d\'expérience dans la vente et la location de villas et appartements de standing.',
                    'description_pro' => 'Expert immobilier certifié, je vous accompagne dans tous vos projets immobiliers à Dakar et ses environs. Mon réseau couvre les quartiers les plus prisés de la capitale : Almadies, Ngor, Mermoz, Sacré-Cœur et le Plateau. Je parle wolof, français et anglais.',
                    'experience'      => '12 ans',
                    'experience_annees' => 12,
                    'disponibilite'   => 'disponible',
                    'is_agent'        => 1,
                    'is_premium'      => 1,
                    'specialites'     => json_encode(['Villas de luxe', 'Appartements standing', 'Investissement locatif']),
                    'zones_intervention' => json_encode(['Almadies', 'Ngor', 'Mermoz', 'Sacré-Cœur', 'Plateau']),
                    'certifications'  => json_encode(['Certification FNAIM Sénégal 2022', 'Formation Droit immobilier UCAD 2019']),
                    'reseaux_sociaux' => json_encode(['facebook' => 'https://facebook.com/moussadialloimmo', 'linkedin' => 'https://linkedin.com/in/moussa-diallo-immo', 'whatsapp' => '+221771234567']),
                    'zones'           => json_encode(['Dakar', 'Almadies', 'Ngor']),
                    'bio'             => 'Né à Dakar, j\'ai commencé ma carrière dans le BTP avant de me spécialiser dans l\'immobilier résidentiel haut de gamme. Mon objectif : vous trouver le bien de vos rêves.',
                ],
            ],
            [
                'user' => [
                    'name'  => 'Fatou Sène',
                    'email' => 'fatou.sene@teranga-immo.sn',
                ],
                'fournisseur' => [
                    'nom'             => 'Sène',
                    'prenom'          => 'Fatou',
                    'adresse'         => 'Mermoz, Rue 10, Dakar',
                    'telephone'       => '+221 78 234 56 78',
                    'name'            => 'Fatou Sène Immobilier',
                    'description'     => 'Consultante immobilière spécialisée en résidentiel familial à Dakar et Pikine. Maîtrise parfaite des procédures administratives et du droit immobilier sénégalais.',
                    'description_pro' => 'Après 8 ans dans le secteur bancaire, j\'ai rejoint l\'immobilier pour accompagner les familles dans l\'acquisition de leur première résidence. Je maîtrise les dispositifs de financement disponibles au Sénégal.',
                    'experience'      => '8 ans',
                    'experience_annees' => 8,
                    'disponibilite'   => 'disponible',
                    'is_agent'        => 1,
                    'is_premium'      => 1,
                    'specialites'     => json_encode(['Résidentiel familial', 'Premier achat', 'Financement immobilier']),
                    'zones_intervention' => json_encode(['Mermoz', 'Liberté', 'HLM', 'Grand Dakar', 'Pikine Nord']),
                    'certifications'  => json_encode(['Diplôme Gestion Immobilière - ESP Dakar 2016', 'Formation Financement Habitat - BHS 2020']),
                    'reseaux_sociaux' => json_encode(['facebook' => 'https://facebook.com/fatoumba.immo', 'instagram' => 'https://instagram.com/fatousene_immo', 'whatsapp' => '+221782345678']),
                    'zones'           => json_encode(['Dakar', 'Pikine', 'Guédiawaye']),
                    'bio'             => 'Passionnée par l\'immobilier familial, j\'aide les ménages sénégalais à réaliser leur rêve de propriété avec les meilleures conditions de financement.',
                ],
            ],
            [
                'user' => [
                    'name'  => 'Ibrahima Ndiaye',
                    'email' => 'ibrahima.ndiaye@teranga-immo.sn',
                ],
                'fournisseur' => [
                    'nom'             => 'Ndiaye',
                    'prenom'          => 'Ibrahima',
                    'adresse'         => 'Plateau, Avenue Léopold Sédar Senghor, Dakar',
                    'telephone'       => '+221 76 345 67 89',
                    'name'            => 'Ndiaye & Associés Immobilier',
                    'description'     => 'Cabinet immobilier de référence au Plateau, spécialisé dans les bureaux, locaux commerciaux et immobilier d\'entreprise à Dakar.',
                    'description_pro' => 'Diplômé en droit des affaires de l\'UCAD, je conseille les entreprises et investisseurs étrangers dans leurs acquisitions immobilières au Sénégal. Maîtrise parfaite du cadre juridique et fiscal.',
                    'experience'      => '15 ans',
                    'experience_annees' => 15,
                    'disponibilite'   => 'disponible',
                    'is_agent'        => 1,
                    'is_premium'      => 1,
                    'specialites'     => json_encode(['Immobilier d\'entreprise', 'Bureaux et locaux', 'Investissement étranger', 'Droit immobilier']),
                    'zones_intervention' => json_encode(['Plateau', 'Point E', 'Fann', 'Zone industrielle de Dakar']),
                    'certifications'  => json_encode(['Master Droit des Affaires - UCAD 2009', 'Agrément ADIE 2015', 'Certification FNAIM International 2021']),
                    'reseaux_sociaux' => json_encode(['linkedin' => 'https://linkedin.com/in/ibrahima-ndiaye-immo', 'whatsapp' => '+221763456789', 'site' => 'https://ndiaye-immobilier.sn']),
                    'zones'           => json_encode(['Dakar Plateau', 'Point E', 'Fann']),
                    'bio'             => 'Fondateur de Ndiaye & Associés, je mets mon expertise juridique et commerciale au service des projets immobiliers les plus complexes.',
                    'site'            => 'https://ndiaye-immobilier.sn',
                ],
            ],
            [
                'user' => [
                    'name'  => 'Aminata Traoré',
                    'email' => 'aminata.traore@teranga-immo.sn',
                ],
                'fournisseur' => [
                    'nom'             => 'Traoré',
                    'prenom'          => 'Aminata',
                    'adresse'         => 'Thiès Nord, Cité Lamy',
                    'telephone'       => '+221 77 456 78 90',
                    'name'            => 'Aminata Traoré Immo',
                    'description'     => 'Première agence immobilière de la région de Thiès, spécialisée dans l\'habitat social et le résidentiel à Thiès, Mbour et Saly-Portudal.',
                    'description_pro' => 'Ancienne employée du Cadastre de Thiès, je connais parfaitement les procédures foncières régionales. Je vous guide dans vos acquisitions de terrains et de maisons dans toute la région de Thiès.',
                    'experience'      => '10 ans',
                    'experience_annees' => 10,
                    'disponibilite'   => 'disponible',
                    'is_agent'        => 1,
                    'is_premium'      => 0,
                    'specialites'     => json_encode(['Terrains résidentiels', 'Habitat social', 'Immobilier balnéaire']),
                    'zones_intervention' => json_encode(['Thiès', 'Mbour', 'Saly-Portudal', 'Somone', 'Joal-Fadiouth']),
                    'certifications'  => json_encode(['Certificat Gestion Foncière - ENEA Dakar 2014']),
                    'reseaux_sociaux' => json_encode(['facebook' => 'https://facebook.com/aminata.traore.immo.thies', 'whatsapp' => '+221774567890']),
                    'zones'           => json_encode(['Thiès', 'Mbour', 'Saly']),
                    'bio'             => 'Fière de contribuer au développement immobilier de ma région natale, je propose des biens accessibles et bien documentés dans toute la région de Thiès.',
                ],
            ],
            [
                'user' => [
                    'name'  => 'Cheikh Mbaye',
                    'email' => 'cheikh.mbaye@teranga-immo.sn',
                ],
                'fournisseur' => [
                    'nom'             => 'Mbaye',
                    'prenom'          => 'Cheikh',
                    'adresse'         => 'Saint-Louis, Quartier Nord',
                    'telephone'       => '+221 33 961 22 33',
                    'name'            => 'Saint-Louis Immobilier',
                    'description'     => 'Agence spécialisée dans l\'immobilier de la ville de Saint-Louis, ville classée UNESCO. Réhabilitation, location saisonnière et vente de maisons coloniales.',
                    'description_pro' => 'Fils de Saint-Louis, je suis passionné par le patrimoine architectural unique de ma ville. Je vous accompagne dans l\'acquisition et la réhabilitation de maisons coloniales inscrites au patrimoine UNESCO.',
                    'experience'      => '7 ans',
                    'experience_annees' => 7,
                    'disponibilite'   => 'disponible',
                    'is_agent'        => 1,
                    'is_premium'      => 0,
                    'specialites'     => json_encode(['Maisons coloniales', 'Patrimoine UNESCO', 'Location saisonnière', 'Réhabilitation']),
                    'zones_intervention' => json_encode(['Saint-Louis', 'Île de Saint-Louis', 'Rao', 'Dagana']),
                    'certifications'  => json_encode(['Formation Patrimoine Architectural - Institut Français 2018']),
                    'reseaux_sociaux' => json_encode(['facebook' => 'https://facebook.com/saintlouisimmobilier', 'whatsapp' => '+221339612233']),
                    'zones'           => json_encode(['Saint-Louis', 'Dagana']),
                    'bio'             => 'Ambassadeur du patrimoine immobilier de Saint-Louis, je valorise les joyaux architecturaux de la vieille ville auprès des acheteurs locaux et internationaux.',
                ],
            ],
            [
                'user' => [
                    'name'  => 'Rokhaya Diop',
                    'email' => 'rokhaya.diop@teranga-immo.sn',
                ],
                'fournisseur' => [
                    'nom'             => 'Diop',
                    'prenom'          => 'Rokhaya',
                    'adresse'         => 'Ouakam, Villa 47, Dakar',
                    'telephone'       => '+221 78 567 89 01',
                    'name'            => 'Rokhaya Diop Immobilier',
                    'description'     => 'Consultante freelance spécialisée dans la diaspora sénégalaise. Accompagnement complet des Sénégalais de l\'étranger dans leurs projets immobiliers.',
                    'description_pro' => 'Ancienne émigrée revenue au Sénégal, je comprends parfaitement les besoins et contraintes de la diaspora. Je gère tous les aspects de votre projet à distance : recherche, visites filmées, gestion administrative et suivi des travaux.',
                    'experience'      => '6 ans',
                    'experience_annees' => 6,
                    'disponibilite'   => 'disponible',
                    'is_agent'        => 1,
                    'is_premium'      => 0,
                    'specialites'     => json_encode(['Diaspora sénégalaise', 'Gestion à distance', 'Investissement locatif']),
                    'zones_intervention' => json_encode(['Ouakam', 'Yoff', 'Parcelles Assainies', 'Keur Massar', 'Diamniadio']),
                    'certifications'  => json_encode(['Certification Agent Immobilier - Chambre des Métiers Dakar 2019']),
                    'reseaux_sociaux' => json_encode(['facebook' => 'https://facebook.com/rokhaya.diaspora.immo', 'instagram' => 'https://instagram.com/rokhi_immo', 'whatsapp' => '+221785678901']),
                    'zones'           => json_encode(['Dakar', 'Diamniadio', 'Keur Massar']),
                    'bio'             => 'Je suis le pont entre la diaspora et l\'immobilier sénégalais. Votre projet au Sénégal est entre de bonnes mains, même depuis Paris, New York ou Madrid.',
                ],
            ],
            [
                'user' => [
                    'name'  => 'Ousmane Konaté',
                    'email' => 'ousmane.konate@teranga-immo.sn',
                ],
                'fournisseur' => [
                    'nom'             => 'Konaté',
                    'prenom'          => 'Ousmane',
                    'adresse'         => 'Ziguinchor, Quartier Boucotte',
                    'telephone'       => '+221 77 678 90 12',
                    'name'            => 'Casamance Immobilier',
                    'description'     => 'La référence immobilière de Ziguinchor et de la Casamance. Terrains, maisons, lodges touristiques et résidences en bord de Casamance.',
                    'description_pro' => 'Natif de Ziguinchor, je valorise les richesses naturelles et architecturales de la Casamance pour les acheteurs locaux, nationaux et internationaux. Spécialiste des lodges et résidences écotouristiques.',
                    'experience'      => '9 ans',
                    'experience_annees' => 9,
                    'disponibilite'   => 'disponible',
                    'is_agent'        => 1,
                    'is_premium'      => 0,
                    'specialites'     => json_encode(['Immobilier touristique', 'Lodges et écolodges', 'Terrains Casamance']),
                    'zones_intervention' => json_encode(['Ziguinchor', 'Bignona', 'Oussouye', 'Cap Skirring', 'Kafountine']),
                    'certifications'  => json_encode(['Formation Tourisme Durable - IRTS Ziguinchor 2017']),
                    'reseaux_sociaux' => json_encode(['facebook' => 'https://facebook.com/casamance.immobilier', 'whatsapp' => '+221776789012']),
                    'zones'           => json_encode(['Ziguinchor', 'Bignona', 'Oussouye']),
                    'bio'             => 'La Casamance recèle des trésors immobiliers encore peu exploités. Je vous aide à investir dans l\'un des endroits les plus beaux du Sénégal.',
                ],
            ],
            [
                'user' => [
                    'name'  => 'Mariama Baldé',
                    'email' => 'mariama.balde@teranga-immo.sn',
                ],
                'fournisseur' => [
                    'nom'             => 'Baldé',
                    'prenom'          => 'Mariama',
                    'adresse'         => 'Liberté 6, Villa 23, Dakar',
                    'telephone'       => '+221 76 789 01 23',
                    'name'            => 'Immo Plus Sénégal',
                    'description'     => 'Agence dynamique spécialisée dans le résidentiel intermédiaire à Dakar. Appartements, studios et maisons pour les classes moyennes et les jeunes actifs.',
                    'description_pro' => 'Je crois en l\'immobilier accessible pour tous les Sénégalais. Ma spécialité : dénicher les bonnes affaires dans les quartiers résidentiels de Dakar pour les primo-accédants et les investisseurs à budget maîtrisé.',
                    'experience'      => '5 ans',
                    'experience_annees' => 5,
                    'disponibilite'   => 'disponible',
                    'is_agent'        => 1,
                    'is_premium'      => 0,
                    'specialites'     => json_encode(['Studio et T2', 'Primo-accédants', 'Résidentiel intermédiaire']),
                    'zones_intervention' => json_encode(['Liberté', 'HLM', 'Médina', 'Biscuiterie', 'Parcelles Assainies']),
                    'certifications'  => json_encode(['BTS Commerce - ISCAM Dakar 2018']),
                    'reseaux_sociaux' => json_encode(['instagram' => 'https://instagram.com/immoplus_senegal', 'tiktok' => 'https://tiktok.com/@immoplus_sn', 'whatsapp' => '+221767890123']),
                    'zones'           => json_encode(['Dakar', 'Pikine']),
                    'bio'             => 'Jeune et dynamique, je suis connectée aux nouvelles tendances du marché immobilier dakarois. Je trouve le bien qui correspond exactement à votre budget.',
                ],
            ],
        ];

        foreach ($agents as $data) {
            // Créer l'utilisateur
            $userId = DB::table('users')->insertGetId([
                'name'              => $data['user']['name'],
                'email'             => $data['user']['email'],
                'password'          => Hash::make('password123'),
                'is_admin'          => 0,
                'status'            => 1,
                'email_verified_at' => now(),
                'created_at'        => now(),
                'updated_at'        => now(),
            ]);

            // Créer le fournisseur
            $f = $data['fournisseur'];
            DB::table('fournisseurs')->insert([
                'user_id'             => $userId,
                'nom'                 => $f['nom'],
                'prenom'              => $f['prenom'],
                'adresse'             => $f['adresse'],
                'telephone'           => $f['telephone'],
                'name'                => $f['name'],
                'description'         => $f['description'],
                'description_pro'     => $f['description_pro'],
                'experience'          => $f['experience'],
                'experience_annees'   => $f['experience_annees'],
                'disponibilite'       => $f['disponibilite'],
                'is_agent'            => $f['is_agent'],
                'is_premium'          => $f['is_premium'],
                'specialites'         => $f['specialites'],
                'zones_intervention'  => $f['zones_intervention'],
                'certifications'      => $f['certifications'],
                'reseaux_sociaux'     => $f['reseaux_sociaux'],
                'zones'               => $f['zones'],
                'bio'                 => $f['bio'],
                'site'                => $f['site'] ?? null,
                'status'              => 1,
                'created_at'          => now(),
                'updated_at'          => now(),
            ]);
        }
    }
}
