<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;

class AnnoncesSeeder extends Seeder
{
    public function run()
    {
        // Nettoyer les données existantes du seeder avant de réinsérer
        DB::table('images')->where('imageable_type', 'App\\Models\\Annonce')
            ->whereIn('imageable_id', DB::table('annonces')->whereNotNull('fournisseur_id')->pluck('id'))
            ->delete();
        DB::table('annonces')->whereNotNull('fournisseur_id')->delete();

        $annonces = [
            // ── DAKAR - ALMADIES ──────────────────────────────────────────────
            [
                'titre'       => 'Villa de standing avec piscine aux Almadies',
                'description' => 'Magnifique villa de 5 chambres aux Almadies, à 200m de la mer. Finitions haut de gamme, piscine privée, double garage, salon avec vue panoramique sur l\'Atlantique. Idéale pour expatriés ou famille aisée. Groupe électrogène et gardiennage inclus.',
                'adresse'     => 'Route de Ngor, Almadies, Dakar',
                'commune'     => 'Almadies',
                'departement' => 'Dakar',
                'prix'        => 350000000,
                'type_loc'    => 'À Vendre',
                'type_immo'   => 'Villa',
                'superficie'  => 450,
                'chambres'    => 5,
                'toillettes'  => 4,
                'salons'      => 2,
                'cuisines'    => 1,
                'meubles'     => 0,
                'is_premium'  => 1,
                'comodites'   => ['Piscine', 'Parking couvert', 'Gardiennage 24h/24', 'Groupe électrogène', 'Climatisation', 'Système d\'alarme', 'Terrasse', 'Jardin'],
                'lat'         => '14.7418',
                'lon'         => '-17.5073',
                'agent_index' => 0,
            ],
            [
                'titre'       => 'Appartement T3 meublé aux Almadies - Vue mer',
                'description' => 'Bel appartement T3 entièrement meublé au 3ème étage avec vue sur la mer. Cuisine américaine équipée, 2 chambres, balcon filant. Résidence sécurisée avec gardien. Idéal pour location courte durée ou résidence secondaire.',
                'adresse'     => 'Résidence Les Almadies, Route des Almadies, Dakar',
                'commune'     => 'Almadies',
                'departement' => 'Dakar',
                'prix'        => 850000,
                'type_loc'    => 'À Louer',
                'type_immo'   => 'Appartement',
                'superficie'  => 110,
                'chambres'    => 2,
                'toillettes'  => 2,
                'salons'      => 1,
                'cuisines'    => 1,
                'meubles'     => 1,
                'is_premium'  => 1,
                'comodites'   => ['Climatisation', 'Balcon', 'Gardiennage 24h/24', 'Parking couvert', 'Fibre optique'],
                'lat'         => '14.7445',
                'lon'         => '-17.5120',
                'agent_index' => 0,
            ],

            // ── DAKAR - MERMOZ / SACRÉ-CŒUR ─────────────────────────────────
            [
                'titre'       => 'Appartement F4 à Mermoz - Résidence calme',
                'description' => 'Spacieux appartement de 4 pièces dans une résidence de standing à Mermoz. Salon double, 3 chambres, cuisine séparée, parking. Quartier sécurisé, proche des ambassades et des commerces. Disponible immédiatement.',
                'adresse'     => 'Cité Mermoz, Rue 10 × Avenue Cheikh Anta Diop, Dakar',
                'commune'     => 'Mermoz-Sacré-Cœur',
                'departement' => 'Dakar',
                'prix'        => 650000,
                'type_loc'    => 'À Louer',
                'type_immo'   => 'Appartement',
                'superficie'  => 140,
                'chambres'    => 3,
                'toillettes'  => 2,
                'salons'      => 1,
                'cuisines'    => 1,
                'meubles'     => 0,
                'is_premium'  => 0,
                'comodites'   => ['Climatisation', 'Parking couvert', 'Gardiennage 24h/24', 'Groupe électrogène'],
                'lat'         => '14.7254',
                'lon'         => '-17.4917',
                'agent_index' => 1,
            ],
            [
                'titre'       => 'Villa R+1 à Sacré-Cœur 3 - 6 chambres',
                'description' => 'Grande villa familiale à Sacré-Cœur 3, deux niveaux, 6 chambres avec dressing, 4 salles de bain, 3 salons, cuisine équipée, jardin, 3 garages. Titre foncier disponible. Quartier résidentiel prisé, proche de toutes commodités.',
                'adresse'     => 'Sacré-Cœur 3, Villa 189, Dakar',
                'commune'     => 'Mermoz-Sacré-Cœur',
                'departement' => 'Dakar',
                'prix'        => 280000000,
                'type_loc'    => 'À Vendre',
                'type_immo'   => 'Villa',
                'superficie'  => 380,
                'chambres'    => 6,
                'toillettes'  => 4,
                'salons'      => 3,
                'cuisines'    => 1,
                'meubles'     => 0,
                'is_premium'  => 1,
                'comodites'   => ['Climatisation', 'Jardin', 'Parking couvert', 'Groupe électrogène', 'Système d\'alarme', 'Vidéosurveillance'],
                'lat'         => '14.7268',
                'lon'         => '-17.4882',
                'agent_index' => 1,
            ],

            // ── DAKAR - PLATEAU ──────────────────────────────────────────────
            [
                'titre'       => 'Bureau 250m² au Plateau - Vue sur Médina',
                'description' => 'Plateau de bureaux de 250m² au 5ème étage d\'un immeuble moderne. Open space modulable, salle de réunion, kitchenette, 8 parkings. Accès facile depuis l\'Avenue William Ponty. Idéal pour grande entreprise ou cabinet.',
                'adresse'     => 'Avenue William Ponty, Dakar Plateau',
                'commune'     => 'Dakar Plateau',
                'departement' => 'Dakar',
                'prix'        => 2800000,
                'type_loc'    => 'À Louer',
                'type_immo'   => 'Bureau',
                'superficie'  => 250,
                'chambres'    => 0,
                'toillettes'  => 3,
                'salons'      => 0,
                'cuisines'    => 1,
                'meubles'     => 1,
                'is_premium'  => 1,
                'comodites'   => ['Climatisation', 'Ascenseur', 'Parking couvert', 'Fibre optique', 'Groupe électrogène', 'Vidéosurveillance'],
                'lat'         => '14.6862',
                'lon'         => '-17.4480',
                'agent_index' => 2,
            ],
            [
                'titre'       => 'Local commercial 80m² au Plateau',
                'description' => 'Local commercial idéalement situé en rez-de-chaussée d\'un immeuble de standing au Plateau. Vitrine sur rue, arrière-boutique, sanitaires. Fort passage piéton. Idéal pour boutique, agence ou restaurant.',
                'adresse'     => 'Avenue Léopold Sédar Senghor, Plateau, Dakar',
                'commune'     => 'Dakar Plateau',
                'departement' => 'Dakar',
                'prix'        => 900000,
                'type_loc'    => 'À Louer',
                'type_immo'   => 'Local commercial',
                'superficie'  => 80,
                'chambres'    => 0,
                'toillettes'  => 1,
                'salons'      => 0,
                'cuisines'    => 0,
                'meubles'     => 0,
                'is_premium'  => 0,
                'comodites'   => ['Climatisation', 'Groupe électrogène'],
                'lat'         => '14.6893',
                'lon'         => '-17.4447',
                'agent_index' => 2,
            ],

            // ── DAKAR - OUAKAM / NGOR ────────────────────────────────────────
            [
                'titre'       => 'Villa bord de mer à Ngor - 4 chambres',
                'description' => 'Villa de caractère à Ngor, à 50m de la plage. Terrain de 400m², 4 chambres, 3 salles de bain, grande terrasse avec vue mer. Grenier aménageable. Très rare sur le marché. Titre foncier propre.',
                'adresse'     => 'Ngor, Face Résidence ACI, Dakar',
                'commune'     => 'Ngor',
                'departement' => 'Dakar',
                'prix'        => 220000000,
                'type_loc'    => 'À Vendre',
                'type_immo'   => 'Villa',
                'superficie'  => 280,
                'chambres'    => 4,
                'toillettes'  => 3,
                'salons'      => 2,
                'cuisines'    => 1,
                'meubles'     => 0,
                'is_premium'  => 1,
                'comodites'   => ['Terrasse', 'Jardins', 'Parking couvert', 'Système d\'alarme'],
                'lat'         => '14.7511',
                'lon'         => '-17.5154',
                'agent_index' => 0,
            ],
            [
                'titre'       => 'Studio meublé à Ouakam - Proche mer',
                'description' => 'Joli studio entièrement meublé à Ouakam, quartier calme. Lit double, coin salon, cuisine équipée, salle de bain moderne. Climatisation. Proximité de la plage et des restaurants. Idéal jeune cadre ou étudiant.',
                'adresse'     => 'Ouakam, Cité Mixte, Dakar',
                'commune'     => 'Ouakam',
                'departement' => 'Dakar',
                'prix'        => 200000,
                'type_loc'    => 'À Louer',
                'type_immo'   => 'Studio',
                'superficie'  => 35,
                'chambres'    => 1,
                'toillettes'  => 1,
                'salons'      => 0,
                'cuisines'    => 1,
                'meubles'     => 1,
                'is_premium'  => 0,
                'comodites'   => ['Climatisation', 'Cuisine équipée'],
                'lat'         => '14.7363',
                'lon'         => '-17.4935',
                'agent_index' => 5,
            ],

            // ── DAKAR - LIBERTÉ / HLM ────────────────────────────────────────
            [
                'titre'       => 'Appartement T3 à Liberté 6 - Non meublé',
                'description' => 'Appartement neuf de 3 pièces au 2ème étage dans un bel immeuble à Liberté 6. Salon, 2 chambres, cuisine séparée, balcon, parking. Gardien de nuit. Quartier vivant et bien desservi par les transports.',
                'adresse'     => 'Liberté 6, Immeuble Tall, Dakar',
                'commune'     => 'Liberté',
                'departement' => 'Dakar',
                'prix'        => 350000,
                'type_loc'    => 'À Louer',
                'type_immo'   => 'Appartement',
                'superficie'  => 90,
                'chambres'    => 2,
                'toillettes'  => 1,
                'salons'      => 1,
                'cuisines'    => 1,
                'meubles'     => 0,
                'is_premium'  => 0,
                'comodites'   => ['Climatisation', 'Balcon', 'Gardiennage 24h/24'],
                'lat'         => '14.7063',
                'lon'         => '-17.4652',
                'agent_index' => 7,
            ],
            [
                'titre'       => 'Terrain 250m² titré à HLM Grand Yoff',
                'description' => 'Terrain de 250m² avec titre foncier en règle à HLM Grand Yoff. Viabilisé, eau et électricité disponibles. Possibilité de construire R+3. Idéal pour construction personnelle ou promotion immobilière.',
                'adresse'     => 'HLM Grand Yoff, Lot 47, Dakar',
                'commune'     => 'HLM',
                'departement' => 'Dakar',
                'prix'        => 45000000,
                'type_loc'    => 'À Vendre',
                'type_immo'   => 'Terrain',
                'superficie'  => 250,
                'chambres'    => 0,
                'toillettes'  => 0,
                'salons'      => 0,
                'cuisines'    => 0,
                'meubles'     => 0,
                'is_premium'  => 0,
                'comodites'   => [],
                'lat'         => '14.7180',
                'lon'         => '-17.4623',
                'agent_index' => 1,
            ],

            // ── DAKAR - PARCELLES ASSAINIES ──────────────────────────────────
            [
                'titre'       => 'Maison familiale aux Parcelles Assainies - 4 chambres',
                'description' => 'Jolie maison familiale aux Parcelles Assainies, Unité 11. Rez-de-chaussée + 1 étage, 4 chambres, 3 salles de bain, grand salon, cuisine spacieuse, cour intérieure, parking 2 voitures. Titre foncier, eau, électricité.',
                'adresse'     => 'Parcelles Assainies, Unité 11, Villa 34, Dakar',
                'commune'     => 'Parcelles Assainies',
                'departement' => 'Dakar',
                'prix'        => 95000000,
                'type_loc'    => 'À Vendre',
                'type_immo'   => 'Maison',
                'superficie'  => 200,
                'chambres'    => 4,
                'toillettes'  => 3,
                'salons'      => 1,
                'cuisines'    => 1,
                'meubles'     => 0,
                'is_premium'  => 0,
                'comodites'   => ['Climatisation', 'Parking couvert', 'Jardin', 'Eau chaude'],
                'lat'         => '14.7617',
                'lon'         => '-17.4522',
                'agent_index' => 7,
            ],

            // ── PIKINE ───────────────────────────────────────────────────────
            [
                'titre'       => 'Appartement T2 à Pikine Nord - Premier achat',
                'description' => 'Appartement idéal pour un premier achat ou investissement locatif à Pikine Nord. T2 avec salon, chambre, douche, cuisine. Quartier dynamique proche du marché. Prix négociable.',
                'adresse'     => 'Pikine Nord, Cité Soprim, Dakar Banlieue',
                'commune'     => 'Pikine Nord',
                'departement' => 'Pikine',
                'prix'        => 18000000,
                'type_loc'    => 'À Vendre',
                'type_immo'   => 'Appartement',
                'superficie'  => 55,
                'chambres'    => 1,
                'toillettes'  => 1,
                'salons'      => 1,
                'cuisines'    => 1,
                'meubles'     => 0,
                'is_premium'  => 0,
                'comodites'   => ['Eau chaude'],
                'lat'         => '14.7538',
                'lon'         => '-17.3858',
                'agent_index' => 1,
            ],
            [
                'titre'       => 'Location maison 3 pièces à Yeumbeul Nord',
                'description' => 'Maison en location à Yeumbeul Nord. Salon, 2 chambres, cuisine, douche externe, cour clôturée. Proche de la route nationale. Accessible et calme. Idéale pour une famille de taille moyenne.',
                'adresse'     => 'Yeumbeul Nord, Zone B, Dakar Banlieue',
                'commune'     => 'Yeumbeul Nord',
                'departement' => 'Pikine',
                'prix'        => 90000,
                'type_loc'    => 'À Louer',
                'type_immo'   => 'Maison',
                'superficie'  => 80,
                'chambres'    => 2,
                'toillettes'  => 1,
                'salons'      => 1,
                'cuisines'    => 1,
                'meubles'     => 0,
                'is_premium'  => 0,
                'comodites'   => [],
                'lat'         => '14.7732',
                'lon'         => '-17.3544',
                'agent_index' => 1,
            ],

            // ── DIAMNIADIO ───────────────────────────────────────────────────
            [
                'titre'       => 'Terrain 500m² viabilisé à Diamniadio - Investissement',
                'description' => 'Terrain de 500m² entièrement viabilisé dans la nouvelle ville de Diamniadio. Eau, électricité, réseau téléphonique. Zone résidentielle R+3 autorisé. Fort potentiel de plus-value à 5 ans. Titre foncier disponible.',
                'adresse'     => 'Diamniadio, Zone Résidentielle C, Rufisque',
                'commune'     => 'Diamniadio',
                'departement' => 'Rufisque',
                'prix'        => 25000000,
                'type_loc'    => 'À Vendre',
                'type_immo'   => 'Terrain',
                'superficie'  => 500,
                'chambres'    => 0,
                'toillettes'  => 0,
                'salons'      => 0,
                'cuisines'    => 0,
                'meubles'     => 0,
                'is_premium'  => 0,
                'comodites'   => [],
                'lat'         => '14.7296',
                'lon'         => '-17.1895',
                'agent_index' => 5,
            ],
            [
                'titre'       => 'Villa neuve à Diamniadio - 3 chambres clé en main',
                'description' => 'Villa neuve R+1 construite par un promoteur sénégalais à Diamniadio. 3 chambres, 2 salles de bain, salon, cuisine équipée, garage. Finitions soignées, résidence fermée avec gardiennage. Livraison immédiate.',
                'adresse'     => 'Résidence Keur Samba, Diamniadio',
                'commune'     => 'Diamniadio',
                'departement' => 'Rufisque',
                'prix'        => 65000000,
                'type_loc'    => 'À Vendre',
                'type_immo'   => 'Villa',
                'superficie'  => 160,
                'chambres'    => 3,
                'toillettes'  => 2,
                'salons'      => 1,
                'cuisines'    => 1,
                'meubles'     => 0,
                'is_premium'  => 1,
                'comodites'   => ['Climatisation', 'Parking couvert', 'Gardiennage 24h/24', 'Groupe électrogène', 'Panneau solaire'],
                'lat'         => '14.7311',
                'lon'         => '-17.1880',
                'agent_index' => 5,
            ],

            // ── THIÈS ────────────────────────────────────────────────────────
            [
                'titre'       => 'Villa 4 chambres à Thiès Nord - Cité Lamy',
                'description' => 'Belle villa en vente à Thiès Nord, Cité Lamy. 4 chambres, 3 salles de bain, double salon, cuisine moderne, cour avec jardin, garage 2 voitures. Titre foncier. Quartier calme et résidentiel, proche des écoles et hôpitaux.',
                'adresse'     => 'Cité Lamy, Thiès Nord',
                'commune'     => 'Thiès Nord',
                'departement' => 'Thiès',
                'prix'        => 75000000,
                'type_loc'    => 'À Vendre',
                'type_immo'   => 'Villa',
                'superficie'  => 220,
                'chambres'    => 4,
                'toillettes'  => 3,
                'salons'      => 2,
                'cuisines'    => 1,
                'meubles'     => 0,
                'is_premium'  => 1,
                'comodites'   => ['Climatisation', 'Jardin', 'Parking couvert', 'Groupe électrogène', 'Eau chaude'],
                'lat'         => '14.7942',
                'lon'         => '-16.9244',
                'agent_index' => 3,
            ],
            [
                'titre'       => 'Terrain 300m² à Thiès Ouest - Zone habitée',
                'description' => 'Terrain de 300m² avec délibération à Thiès Ouest. Quartier résidentiel développé, eau et électricité en bordure. Accès route bitumée. Voisinage déjà bâti. Idéal pour maison individuelle.',
                'adresse'     => 'Thiès Ouest, Quartier Diakhao',
                'commune'     => 'Thiès Ouest',
                'departement' => 'Thiès',
                'prix'        => 12000000,
                'type_loc'    => 'À Vendre',
                'type_immo'   => 'Terrain',
                'superficie'  => 300,
                'chambres'    => 0,
                'toillettes'  => 0,
                'salons'      => 0,
                'cuisines'    => 0,
                'meubles'     => 0,
                'is_premium'  => 0,
                'comodites'   => [],
                'lat'         => '14.7874',
                'lon'         => '-16.9338',
                'agent_index' => 3,
            ],

            // ── SALY-PORTUDAL / MBOUR ────────────────────────────────────────
            [
                'titre'       => 'Villa balnéaire à Saly - Piscine et jardin tropical',
                'description' => 'Superbe villa balnéaire à Saly-Portudal. 4 chambres climatisées, toutes en suite, piscine privée 8x4m, jardin tropical de 800m², terrasse couverte, salon avec vue jardin. Personnel de maison disponible. Rendement locatif excellent.',
                'adresse'     => 'Saly-Portudal, Lot Balnéaire 23, Mbour',
                'commune'     => 'Ngaparou',
                'departement' => 'Mbour',
                'prix'        => 185000000,
                'type_loc'    => 'À Vendre',
                'type_immo'   => 'Villa',
                'superficie'  => 320,
                'chambres'    => 4,
                'toillettes'  => 4,
                'salons'      => 2,
                'cuisines'    => 1,
                'meubles'     => 1,
                'is_premium'  => 1,
                'comodites'   => ['Piscine', 'Jardin', 'Climatisation', 'Groupe électrogène', 'Terrasse', 'Parking couvert', 'Système d\'alarme', 'Eau chaude'],
                'lat'         => '14.4532',
                'lon'         => '-17.0007',
                'agent_index' => 3,
            ],
            [
                'titre'       => 'Location saisonnière villa à Somone - 3 chambres',
                'description' => 'Villa en location saisonnière à Somone, à 300m de la lagune. 3 chambres climatisées, salon avec TV satellite, cuisine équipée, terrasse, parking. Disponible toute l\'année. Tarif mensuel : 750 000 CFA.',
                'adresse'     => 'Somone, Résidence Le Baobab, Mbour',
                'commune'     => 'Somone',
                'departement' => 'Mbour',
                'prix'        => 750000,
                'type_loc'    => 'À Louer',
                'type_immo'   => 'Villa',
                'superficie'  => 180,
                'chambres'    => 3,
                'toillettes'  => 2,
                'salons'      => 1,
                'cuisines'    => 1,
                'meubles'     => 1,
                'is_premium'  => 0,
                'comodites'   => ['Climatisation', 'Cuisine équipée', 'Terrasse', 'Parking couvert'],
                'lat'         => '14.4781',
                'lon'         => '-17.0159',
                'agent_index' => 3,
            ],

            // ── SAINT-LOUIS ──────────────────────────────────────────────────
            [
                'titre'       => 'Maison coloniale à vendre - Île de Saint-Louis UNESCO',
                'description' => 'Rare opportunité : maison coloniale du XIXème siècle sur l\'Île de Saint-Louis, classée UNESCO. 3 étages, 6 pièces, balcons en fer forgé, cour intérieure. À réhabiliter. Idéale pour hôtel de charme, restaurant ou résidence de prestige.',
                'adresse'     => 'Île de Saint-Louis, Rue Blanchot',
                'commune'     => 'Saint-Louis',
                'departement' => 'Saint-Louis',
                'prix'        => 55000000,
                'type_loc'    => 'À Vendre',
                'type_immo'   => 'Immeuble',
                'superficie'  => 350,
                'chambres'    => 6,
                'toillettes'  => 4,
                'salons'      => 2,
                'cuisines'    => 1,
                'meubles'     => 0,
                'is_premium'  => 1,
                'comodites'   => ['Terrasse', 'Balcon'],
                'lat'         => '16.0226',
                'lon'         => '-16.4897',
                'agent_index' => 4,
            ],
            [
                'titre'       => 'Appartement meublé à louer à Saint-Louis - Vue fleuve',
                'description' => 'Superbe appartement meublé avec vue directe sur le fleuve Sénégal. 2 chambres, salon, cuisine, terrasse privée. Immeuble neuf en plein cœur de Saint-Louis. Idéal pour séjour professionnel ou touristique.',
                'adresse'     => 'Saint-Louis, Quai Roume, Rive gauche',
                'commune'     => 'Saint-Louis',
                'departement' => 'Saint-Louis',
                'prix'        => 350000,
                'type_loc'    => 'À Louer',
                'type_immo'   => 'Appartement',
                'superficie'  => 95,
                'chambres'    => 2,
                'toillettes'  => 2,
                'salons'      => 1,
                'cuisines'    => 1,
                'meubles'     => 1,
                'is_premium'  => 0,
                'comodites'   => ['Climatisation', 'Terrasse', 'Cuisine équipée', 'Fibre optique'],
                'lat'         => '16.0337',
                'lon'         => '-16.5088',
                'agent_index' => 4,
            ],

            // ── ZIGUINCHOR / CASAMANCE ───────────────────────────────────────
            [
                'titre'       => 'Lodge écotouristique à vendre - Bords du fleuve Casamance',
                'description' => 'Lodge en bois de teck de 8 bungalows sur berge du fleuve Casamance, à 15km de Ziguinchor. Accès pirogue ou route. Restaurant, bar, piscine naturelle. Activité existante, clientèle fidèle. Cession de fond de commerce incluse.',
                'adresse'     => 'Bords du fleuve Casamance, Niaguis, Ziguinchor',
                'commune'     => 'Niaguis',
                'departement' => 'Ziguinchor',
                'prix'        => 120000000,
                'type_loc'    => 'À Vendre',
                'type_immo'   => 'Immeuble',
                'superficie'  => 1200,
                'chambres'    => 8,
                'toillettes'  => 8,
                'salons'      => 1,
                'cuisines'    => 1,
                'meubles'     => 1,
                'is_premium'  => 1,
                'comodites'   => ['Jardin', 'Piscine', 'Panneau solaire', 'Parking couvert', 'Terrasse'],
                'lat'         => '12.5162',
                'lon'         => '-16.4114',
                'agent_index' => 6,
            ],
            [
                'titre'       => 'Terrain 1000m² à Oussouye - Vue sur la mangrove',
                'description' => 'Grand terrain de 1000m² à Oussouye, en bordure de la forêt de mangroves. Vue imprenable, brise de mer. Délibération communale. Idéal pour villa privée ou écolodge. Zone calme et préservée.',
                'adresse'     => 'Oussouye, Secteur Cabrousse',
                'commune'     => 'Oussouye',
                'departement' => 'Oussouye',
                'prix'        => 8000000,
                'type_loc'    => 'À Vendre',
                'type_immo'   => 'Terrain',
                'superficie'  => 1000,
                'chambres'    => 0,
                'toillettes'  => 0,
                'salons'      => 0,
                'cuisines'    => 0,
                'meubles'     => 0,
                'is_premium'  => 0,
                'comodites'   => [],
                'lat'         => '12.4837',
                'lon'         => '-16.5438',
                'agent_index' => 6,
            ],

            // ── KAOLACK ──────────────────────────────────────────────────────
            [
                'titre'       => 'Immeuble R+2 à Kaolack Centre - Rendement locatif',
                'description' => 'Immeuble de rapport à Kaolack Centre, R+2, composé de 6 appartements T3 et 2 commerces en rez-de-chaussée. Tous occupés, rendement locatif brut 7%. Titre foncier. Idéal investisseur cherchant revenus réguliers.',
                'adresse'     => 'Kaolack Centre, Rue du Commerce',
                'commune'     => 'Kaolack',
                'departement' => 'Kaolack',
                'prix'        => 145000000,
                'type_loc'    => 'À Vendre',
                'type_immo'   => 'Immeuble',
                'superficie'  => 600,
                'chambres'    => 12,
                'toillettes'  => 8,
                'salons'      => 6,
                'cuisines'    => 6,
                'meubles'     => 0,
                'is_premium'  => 0,
                'comodites'   => ['Groupe électrogène', 'Parking couvert'],
                'lat'         => '14.1505',
                'lon'         => '-16.0726',
                'agent_index' => 2,
            ],

            // ── TOUBA ────────────────────────────────────────────────────────
            [
                'titre'       => 'Villa 5 chambres à Touba - Secteur 5',
                'description' => 'Grande villa familiale à Touba Mosquée, Secteur 5. 5 chambres, 4 douches, 2 salons, cuisine moderne, cour extérieure 200m². Générateur, château d\'eau, parking 3 voitures. Construction solide en parpaings. Titre foncier.',
                'adresse'     => 'Touba Mosquée, Secteur 5, Mbacké',
                'commune'     => 'Touba Mosquée',
                'departement' => 'Mbacké',
                'prix'        => 80000000,
                'type_loc'    => 'À Vendre',
                'type_immo'   => 'Villa',
                'superficie'  => 300,
                'chambres'    => 5,
                'toillettes'  => 4,
                'salons'      => 2,
                'cuisines'    => 1,
                'meubles'     => 0,
                'is_premium'  => 0,
                'comodites'   => ['Groupe électrogène', 'Parking couvert', 'Eau chaude'],
                'lat'         => '14.8571',
                'lon'         => '-15.8819',
                'agent_index' => 2,
            ],

            // ── TAMBACOUNDA ──────────────────────────────────────────────────
            [
                'titre'       => 'Maison 3 chambres en location à Tambacounda',
                'description' => 'Maison individuelle en location à Tambacounda, quartier Plateau. 3 chambres, 2 douches, grand salon, cuisine indépendante, cour clôturée, parking. Bâtiment récent, bon état général. Proche des marchés et transports.',
                'adresse'     => 'Tambacounda Plateau, Rue 22',
                'commune'     => 'Tambacounda',
                'departement' => 'Tambacounda',
                'prix'        => 120000,
                'type_loc'    => 'À Louer',
                'type_immo'   => 'Maison',
                'superficie'  => 120,
                'chambres'    => 3,
                'toillettes'  => 2,
                'salons'      => 1,
                'cuisines'    => 1,
                'meubles'     => 0,
                'is_premium'  => 0,
                'comodites'   => ['Climatisation', 'Eau chaude'],
                'lat'         => '13.7676',
                'lon'         => '-13.6688',
                'agent_index' => 2,
            ],

            // ── ZIGUINCHOR - BIGNONA ─────────────────────────────────────────
            [
                'titre'       => 'Villa piscine à louer à Ziguinchor - Quartier Boucotte',
                'description' => 'Belle villa récente en location à Ziguinchor, quartier Boucotte. 3 chambres climatisées, salon, cuisine équipée, piscine privée 6x3m, jardin. Idéale pour famille ou expatriés. Gardien en poste.',
                'adresse'     => 'Boucotte, Ziguinchor',
                'commune'     => 'Ziguinchor',
                'departement' => 'Ziguinchor',
                'prix'        => 500000,
                'type_loc'    => 'À Louer',
                'type_immo'   => 'Villa',
                'superficie'  => 200,
                'chambres'    => 3,
                'toillettes'  => 2,
                'salons'      => 1,
                'cuisines'    => 1,
                'meubles'     => 1,
                'is_premium'  => 0,
                'comodites'   => ['Piscine', 'Climatisation', 'Jardin', 'Gardiennage 24h/24'],
                'lat'         => '12.5610',
                'lon'         => '-16.2659',
                'agent_index' => 6,
            ],

            // ── KOLDA ────────────────────────────────────────────────────────
            [
                'titre'       => 'Terrain 600m² à Kolda Centre - Titre foncier',
                'description' => 'Grand terrain de 600m² à Kolda Centre avec titre foncier. Zone commerciale et résidentielle mixte. Accès route principale. Opportunité rare dans cette ville en plein développement.',
                'adresse'     => 'Kolda Centre, Avenue Askia Mohamed',
                'commune'     => 'Kolda',
                'departement' => 'Kolda',
                'prix'        => 6500000,
                'type_loc'    => 'À Vendre',
                'type_immo'   => 'Terrain',
                'superficie'  => 600,
                'chambres'    => 0,
                'toillettes'  => 0,
                'salons'      => 0,
                'cuisines'    => 0,
                'meubles'     => 0,
                'is_premium'  => 0,
                'comodites'   => [],
                'lat'         => '12.8918',
                'lon'         => '-14.9411',
                'agent_index' => 6,
            ],

            // ── DAKAR - YOFF ─────────────────────────────────────────────────
            [
                'titre'       => 'Villa moderne à Yoff - 4 chambres, proche aéroport AIBD',
                'description' => 'Villa moderne à Yoff, à 10 minutes de l\'Aéroport International Blaise Diagne (AIBD). 4 chambres, 3 salles de bain, grand salon, cuisine américaine, jardin 250m², piscine, double garage. Idéale pour personnel navigant ou famille aisée.',
                'adresse'     => 'Yoff Virage, Villa 48, Dakar',
                'commune'     => 'Yoff',
                'departement' => 'Dakar',
                'prix'        => 195000000,
                'type_loc'    => 'À Vendre',
                'type_immo'   => 'Villa',
                'superficie'  => 290,
                'chambres'    => 4,
                'toillettes'  => 3,
                'salons'      => 2,
                'cuisines'    => 1,
                'meubles'     => 0,
                'is_premium'  => 1,
                'comodites'   => ['Piscine', 'Jardin', 'Climatisation', 'Parking couvert', 'Groupe électrogène', 'Système d\'alarme'],
                'lat'         => '14.7620',
                'lon'         => '-17.4678',
                'agent_index' => 0,
            ],

            // ── RUFISQUE ─────────────────────────────────────────────────────
            [
                'titre'       => 'Appartement T3 à Rufisque Ouest - Résidence Sécurisée',
                'description' => 'Appartement T3 neuf dans une résidence sécurisée à Rufisque Ouest. 2 chambres, salon, cuisine équipée, balcon, 1 parking. Accès direct à l\'autoroute à péage. Idéal pour professionnel travaillant à Dakar ou Diamniadio.',
                'adresse'     => 'Rufisque Ouest, Résidence Sunu Keur',
                'commune'     => 'Rufisque Ouest',
                'departement' => 'Rufisque',
                'prix'        => 28000000,
                'type_loc'    => 'À Vendre',
                'type_immo'   => 'Appartement',
                'superficie'  => 85,
                'chambres'    => 2,
                'toillettes'  => 1,
                'salons'      => 1,
                'cuisines'    => 1,
                'meubles'     => 0,
                'is_premium'  => 0,
                'comodites'   => ['Climatisation', 'Balcon', 'Parking couvert', 'Gardiennage 24h/24'],
                'lat'         => '14.7160',
                'lon'         => '-17.2726',
                'agent_index' => 5,
            ],

            // ── DAKAR - MÉDINA ───────────────────────────────────────────────
            [
                'titre'       => 'Local commercial 120m² à la Médina - Fort passage',
                'description' => 'Local commercial de 120m² en rez-de-chaussée à la Médina, angle de rue à fort passage. Actuellement exploité comme épicerie. Vitrine double, arrière boutique, stockage. Idéal pour commerce alimentaire, pharmacie ou transfert d\'argent.',
                'adresse'     => 'Médina, Rue 19 × Rue 37, Dakar',
                'commune'     => 'Médina',
                'departement' => 'Dakar',
                'prix'        => 600000,
                'type_loc'    => 'À Louer',
                'type_immo'   => 'Local commercial',
                'superficie'  => 120,
                'chambres'    => 0,
                'toillettes'  => 1,
                'salons'      => 0,
                'cuisines'    => 0,
                'meubles'     => 0,
                'is_premium'  => 0,
                'comodites'   => ['Climatisation'],
                'lat'         => '14.6938',
                'lon'         => '-17.4395',
                'agent_index' => 7,
            ],
        ];

        // Images Unsplash par type de bien
        $imageUrls = [
            'Villa'            => 'https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=800',
            'Appartement'      => 'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800',
            'Maison'           => 'https://images.unsplash.com/photo-1570129477492-45c003edd2be?w=800',
            'Bureau'           => 'https://images.unsplash.com/photo-1497366216548-37526070297c?w=800',
            'Local commercial' => 'https://images.unsplash.com/photo-1604328698692-f76ea9498e76?w=800',
            'Immeuble'         => 'https://images.unsplash.com/photo-1486325212027-8081e485255e?w=800',
            'Studio'           => 'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800',
            'Duplex'           => 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800',
            'Terrain'          => 'https://images.unsplash.com/photo-1500382017468-9049fed747ef?w=800',
            'default'          => 'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=800',
        ];

        // Récupérer les IDs de référence
        $typeVente    = DB::table('type_locations')->where('name', 'À Vendre')->first();
        $typeLocation = DB::table('type_locations')->where('name', 'À Louer')->first();
        $fournisseurs = DB::table('fournisseurs')->where('is_agent', 1)->orderBy('id')->get();

        foreach ($annonces as $data) {
            // Commune et Département
            $commune = DB::table('communes')->where('name', $data['commune'])->first();
            $dept    = DB::table('departements')->where('name', $data['departement'])->first();

            // Type immobilier
            $typeImmo = DB::table('type_immos')->where('name', $data['type_immo'])->first();

            // Type location
            $tl = $data['type_loc'] === 'À Vendre' ? $typeVente : $typeLocation;

            // Agent
            $agentIdx   = $data['agent_index'] ?? 0;
            $fournisseur = $fournisseurs[$agentIdx] ?? $fournisseurs->first();

            // Slug unique
            $slug = \Illuminate\Support\Str::slug($data['titre']) . '-' . uniqid();

            $annonceId = DB::table('annonces')->insertGetId([
                'name'              => $data['titre'],
                'description'       => $data['description'],
                'adresse'           => $data['adresse'],
                'prix'              => $data['prix'],
                'lon'               => $data['lon'],
                'lat'               => $data['lat'],
                'superficie'        => $data['superficie'],
                'chambres'          => $data['chambres'],
                'toillettes'        => $data['toillettes'],
                'salons'            => $data['salons'],
                'cuisines'          => $data['cuisines'],
                'meubles'           => $data['meubles'],
                'is_premium'        => $data['is_premium'],
                'is_verify'         => 1,
                'status'            => 1,
                'slug'              => $slug,
                'commune_id'        => $commune?->id,
                'departement_id'    => $dept?->id,
                'type_immo_id'      => $typeImmo?->id,
                'type_location_id'  => $tl?->id,
                'fournisseur_id'    => $fournisseur?->id,
                'comodites'         => json_encode($data['comodites']),
                'date_disponibilite'=> now()->addDays(rand(0, 30))->format('Y-m-d'),
                'created_at'        => now()->subDays(rand(1, 180)),
                'updated_at'        => now(),
            ]);

            // Image principale (Unsplash)
            $imageUrl = $imageUrls[$data['type_immo']] ?? $imageUrls['default'];
            DB::table('images')->insert([
                'url'            => $imageUrl,
                'imageable_id'   => $annonceId,
                'imageable_type' => 'App\\Models\\Annonce',
                'created_at'     => now(),
                'updated_at'     => now(),
            ]);
        }
    }
}
